kind: Deployment
apiVersion: apps/v1
metadata:
  name: helpdesk-backend-app-deployment
spec:
  template:
    spec:
      containers:
        - name: helpdesk-backend-container
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
            exec:
              command:
                - "curl"
                - "--fail"
                - "-o"
                - "/dev/null"
                - "http://localhost/info"
