kind: Deployment
apiVersion: apps/v1
metadata:
  name: helpdesk-backend-app-deployment
  namespace: aras-helpdesk
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%